version: '1.0'

# Services
services:
  # Server service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata: